use std::collections::HashMap;

use lazy_static::lazy_static;
use solana_sdk::pubkey;
use solana_sdk::pubkey::Pubkey;

lazy_static! {
    pub static ref POOL_WITH_NON_PDA_BASED_LP_MINT: HashMap<Pubkey, Pubkey> = HashMap::from_iter([
        (
            pubkey!("H49XALURUKbXRysVXYvHKsd5h4TRbZA2iq9kChVi1JvF"),
            pubkey!("3GgCMTyddNhZd29rKLLfQ86wQcer1CcksEgvYpraF2UH")
        ),
        (
            pubkey!("HcjZvfeSNJbNkfLD4eEcRBr96AD3w1GpmMppaeRZf7ur"),
            pubkey!("B2uEs9zjnz222hfUaUuRgesryUEYwy3JGuWe31sE9gsG")
        ),
        (
            pubkey!("7EJSgV2pthhDfb4UiER9vzTqe2eojei9GEQAQnkqJ96e"),
            pubkey!("9Gpvqcua3hLps1AhtTSVEFSgKG2Dni6yLyXtEeZGLR3y")
        ),
        (
            pubkey!("486t886mRYmo29uubn59PND69ApSbn9ukeLeL2aemLAS"),
            pubkey!("BNqkJsPE1GraPokMMQXoVaZSoAjL1RTNwDcdmsfcjqf4")
        ),
        (
            pubkey!("Aw1MJ31SHEEYmzg9vE4bXa5ZURS5HDvMZjhXmt7Tu8yJ"),
            pubkey!("CVLS1XdDzNBVnQGwhLG5fz3mUur4Zb1KvUbAUa3SJEZN")
        ),
        (
            pubkey!("pvgGDMNpxapbVM8YNao5f6i6mioMzZBHjzDeEcYf9iZ"),
            pubkey!("FdpRVskpa3uR8CR7ggLs7RjpVH1iF5kog6maKTHcTqK1")
        ),
        (
            pubkey!("5fMmLVAtAtMjaXtAWtHPQT83trtDx7kxmgcgJkVPny1K"),
            pubkey!("Bpa1RdNV7ScuaPdVVosQ2UCcHbpr4b9KWQvXJGGKCJ3F")
        ),
        (
            pubkey!("6ZLKLjMd2KzH7PPHCXUPgbMAtdTT37VgTtdeXWLoJppr"),
            pubkey!("3mtMyBrCf48tJ1XmMnoYZgQqqn6VNEYAfKHzGZnfAZPt")
        ),
        (
            pubkey!("Gyv8znLzPb44XatDar8ebx1zG6VvvuPHtaJP8MdCjNoQ"),
            pubkey!("FmQSveFkR6Z2hbkA5WDNwLdo4xdsS1C8gR5bCu8Zpdsu")
        ),
        (
            pubkey!("2X2my7iZEKE7BgqfRVC2a5c5VxekZa2HxGctHyoXxe2m"),
            pubkey!("GX9SZ81En5uSDB5PTL9AAfKfKuqVHiBYJMY5wsex4Zu4")
        ),
        (
            pubkey!("5NLrRmfjaBHj2DpGNihVis6yVv236P8m5AdR838vGMWK"),
            pubkey!("mXZy4YFSKWZ3BdnHjbG9NJknL2PcmAXxF2neUDoFcNq")
        ),
        (
            pubkey!("5kYoik2SHAQxtK82jeHfkwTb1UrStJJUqBteXcU5csP8"),
            pubkey!("B1J8bDBxoUXWk6hpdbcLDw1WQFeBUuiFMyJFwpnxujmp")
        ),
        (
            pubkey!("HCuxikDxMaSvJHoWVy2WaJyvZ5SPnFYZQhRDmtonHrv2"),
            pubkey!("2jWz3vZzCTxLsPjGsuQLLY9hB7RKtA8KiwtBJziqJz9v")
        ),
        (
            pubkey!("4xqyRGWMRkfVo7GH74aryKjSLcpQiVHGAZY4u1n6wAbZ"),
            pubkey!("36F4LM4tK5xSteQnv7DGjkgoyeb7iWjzwGwmxiEUixPC")
        ),
        (
            pubkey!("EdCfPu6685kto9w9xJnwyAsrB1xPVcAzLzyVNW9EwdQS"),
            pubkey!("9i6M6o2NCqUG8jinGrqKb6w172YfX5KBVPFSsSnv1ZXi")
        ),
        (
            pubkey!("5yuefgbJJpmFNK2iiYbLSpv1aZXq7F9AUKkZKErTYCvs"),
            pubkey!("4x76pkvNJYy9YRZM6Y6RZXJckRpsHQEWoD6sM9HEpmB")
        ),
        (
            pubkey!("5NQTw1WqVEt6wP1LmohsrYDyJp2NDipdv6eULVNByXMb"),
            pubkey!("472wjciN9cdAdMAWA3aQXBqTeoX6UV1ahTVELdrcncD2")
        ),
        (
            pubkey!("32D4zRxNc1EssbJieVHfPhZM3rH6CzfUPrWUuWxD9prG"),
            pubkey!("xLebAypjbaQ9tmxUKHV6DZU4mY8ATAAP2sfkNNQLXjf")
        ),
        (
            pubkey!("9CopBY6iQBaZKAhhQANfy7g4VXZkx9zKm8AisPd5Ufay"),
            pubkey!("48w8Bdsz15PzFLuow9bvo3HQWZW4bxdivvpRoTRc3prg")
        ),
        (
            pubkey!("RBtHAB7TS7EDaGVRQHDG6AzK5whz1pQtMiXtrMa5Srn"),
            pubkey!("DkcS27SzJ4sN94eS3Y84u6QPLJ3LM3RfmfDM7NVnwee1")
        ),
        (
            pubkey!("3y6k8aeJxeRX7i3mYtd8G12oqzko1wdjxLJ91roJRnsP"),
            pubkey!("8TEL6fscLwefNbCEKdCNBuVUSSD9JX6aZ6hSP1oqqiY6")
        ),
    ]);
}

#[cfg(feature = "devnet")]
lazy_static! {
    static ref POOL_WITH_NON_PDA_BASED_LP_MINT: HashMap<Pubkey, Pubkey> = HashMap::from_iter([
        (
            pubkey!("GXy2cEDWFodXuXpEZZizVzcyiqF2QZCiMqfZX9BGx1vz"),
            pubkey!("2nqgDcgfTzXJSckrVdqZGFpSfAAUY7NJKhCeikioaP5m")
        ),
        (
            pubkey!("2GPECnGQbXgBBPmmLdw8daxu6A1VJUyuHGWPyJH6U56h"),
            pubkey!("FMnK5dTHUDR9iLvcshaaxnnEtYN1Ly5Gv8e3vccQ8k9K")
        ),
        (
            pubkey!("3PSrJVm8CYJ9R1eJUT9iMikjWD6b8xHWp8VGUnMdr5yF"),
            pubkey!("cu45VVBLEjpwufw4A4FRLmfyckJNwwxmNrf86burdvy")
        ),
        (
            pubkey!("FZgdEqq6rwsWnsZ83Ez2pyJqPdPGfDvzYhrbvcboTPtf"),
            pubkey!("2qWv8R6EBibqTsBCfyiqKaDh3HU8TxwD26cr5zGkFMJs")
        ),
        (
            pubkey!("AyRTAzaXPamTMTRG8dny9jqG3EGWte8FrY5g9Ds3Gtr2"),
            pubkey!("8J65QEAV5c6CREDBpNBYhrKn7zGdoodMj2Nk1mSeUpPz")
        ),
        (
            pubkey!("HK7b7P3goViFkSLQ7rTKRemsGa8LKNKt2t9D4buzbxq2"),
            pubkey!("BJUsjgYod77LrvTpTATwPQwjuk7hHPyNGKYUSVRJmgvN")
        ),
        (
            pubkey!("BAHscmu1NncGS7t4rc5gSBPv1UFEMkvLaon1Ahdd5rHi"),
            pubkey!("3A2DuLdNFyeVFVsumFEVWKFoLaeTryZ4PQSJowD38Le7")
        ),
        (
            pubkey!("2rkn2yM4wJcHPV57T8fPWeBksrfSpiNZoEjRgjtxNDEQ"),
            pubkey!("ENoFQvqrk6LnxRUmPX1cJzHyrsicJCrbZ2WEtGMY9y6N")
        ),
        (
            pubkey!("Bgf1Sy5kfeDgib4go4NgzHuZwek8wE8NZus56z6uizzi"),
            pubkey!("2xSpdNRwDjkx2BJAtdu2zArWybzeEHqPqP1m63tFakNU")
        ),
    ]);
}
