name: CPI example

on:
  pull_request:
    branches:
      - main

jobs:
  program_changed_files:
    runs-on: ubuntu-20.04
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            programs/cpi-example

  cpi_example_test:
    runs-on: ubuntu-20.04
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -- --nocapture
        shell: bash
